# Generated by Django 5.2.1 on 2025-05-14 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_field_updated_at_alter_recruitment_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Application',
                'db_table': 'applications',
            },
        ),
        migrations.CreateModel(
            name='ApplicationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=50)),
            ],
            options={
                'verbose_name': 'Application Field',
                'db_table': 'application_field',
            },
        ),
        migrations.AlterField(
            model_name='recruitmentfield',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_field_set', related_query_name='recruitment_field', to='board.field'),
        ),
        migrations.AlterField(
            model_name='recruitmentfield',
            name='recruitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_field_set', related_query_name='recruitment_field', to='board.recruitment'),
        ),
        migrations.AlterUniqueTogether(
            name='recruitmentfield',
            unique_together={('recruitment', 'field')},
        ),
        migrations.AddIndex(
            model_name='recruitmentfield',
            index=models.Index(fields=['recruitment', 'field'], name='recruitment_recruit_d6170b_idx'),
        ),
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='recruitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_set', to='board.recruitment'),
        ),
        migrations.AddField(
            model_name='applicationfield',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_field_set', related_query_name='application_field', to='board.application'),
        ),
        migrations.AddField(
            model_name='applicationfield',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_field_set', to='board.field'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('applicant', 'recruitment')},
        ),
        migrations.AlterUniqueTogether(
            name='applicationfield',
            unique_together={('application', 'field')},
        ),
    ]
